baseURL = "www.azureworkshops.com"
languageCode = "en-us"
title = "Azure Workshops"
themesDir = "themes"
theme = ["hugo-whisper-theme","reveal-hugo"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Azure Functions"
    url = "/workshops/functions/"
    weight = 2

[params]
  google_analytics_id="UA-140694684-1"
  homepage_button_link = '/workshops/functions'
  homepage_button_text = 'Go to Azure Functions Workshop'
  homepage_intro = 'Azure Workshops is a free workshop repository.'
#  homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "Azure Workshops"
    meta_og_title = "Azure Workshops"
    meta_og_type = "website"
    meta_og_url = "https://www.azureworkshops.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Azure Workshops"
    meta_twitter_card = "summary"
    meta_twitter_site = "@MaximRouiller"
    meta_twitter_creator = "@MaximRouiller"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[reveal_hugo]
theme = "moon"
highlight_theme = "solarized-dark"
slide_number = true
transition = "zoom"